/* Generated By:JavaCC: Do not edit this line. adacConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface adacConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int ALNUM = 7;
  /** RegularExpression Id. */
  int INITCOMMENT = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int LBRACK = 13;
  /** RegularExpression Id. */
  int RBRACK = 14;
  /** RegularExpression Id. */
  int INTDEF = 15;
  /** RegularExpression Id. */
  int BOOLDEF = 16;
  /** RegularExpression Id. */
  int CHARDEF = 17;
  /** RegularExpression Id. */
  int INTVAL = 18;
  /** RegularExpression Id. */
  int CHARVAL = 19;
  /** RegularExpression Id. */
  int BOOLVAL = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int ASSIGNATION = 22;
  /** RegularExpression Id. */
  int ADD = 23;
  /** RegularExpression Id. */
  int SUB = 24;
  /** RegularExpression Id. */
  int MUL = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int MOD = 27;
  /** RegularExpression Id. */
  int EQUAL = 28;
  /** RegularExpression Id. */
  int NOTEQUAL = 29;
  /** RegularExpression Id. */
  int LESSTHAN = 30;
  /** RegularExpression Id. */
  int GREATERTHAN = 31;
  /** RegularExpression Id. */
  int LTOREQUAL = 32;
  /** RegularExpression Id. */
  int GTOREQUAL = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int FUNCTION = 37;
  /** RegularExpression Id. */
  int PROCEDURE = 38;
  /** RegularExpression Id. */
  int IS = 39;
  /** RegularExpression Id. */
  int VALPARAM = 40;
  /** RegularExpression Id. */
  int REFPARAM = 41;
  /** RegularExpression Id. */
  int RETURN = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int THEN = 44;
  /** RegularExpression Id. */
  int ELSE = 45;
  /** RegularExpression Id. */
  int WHILE = 46;
  /** RegularExpression Id. */
  int DO = 47;
  /** RegularExpression Id. */
  int BEGIN = 48;
  /** RegularExpression Id. */
  int END = 49;
  /** RegularExpression Id. */
  int NAME = 50;
  /** RegularExpression Id. */
  int UNKNOWN = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<ALNUM>",
    "<INITCOMMENT>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"integer\"",
    "\"boolean\"",
    "\"character\"",
    "<INTVAL>",
    "<CHARVAL>",
    "<BOOLVAL>",
    "<STRING>",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"function\"",
    "\"procedure\"",
    "\"is\"",
    "\"val\"",
    "\"ref\"",
    "\"return\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"begin\"",
    "\"end\"",
    "<NAME>",
    "<UNKNOWN>",
  };

}
